var miCanvasRojo = document.getElementById("miCanvasRojo");
var contextoRojo = miCanvasRojo.getContext("2d");
contextoRojo.fillStyle = "red";
contextoRojo.fillRect (30, 30, 50, 50);
var miCanvasVerde = document.getElementById("miCanvasVerde");
var contextoVerde = miCanvasVerde.getContext("2d");
contextoVerde.fillStyle = "green";
contextoVerde.fillRect (30, 30, 50, 50);
var miCanvasAzul = document.getElementById("miCanvasAzul");
var contextoAzul = miCanvasAzul.getContext("2d");
contextoAzul.fillStyle = "blue";
contextoAzul.fillRect (30, 30, 50, 50);
