var miCanvasRojo = document.getElementById("miCanvasRojo");
var contextoRojo = miCanvasRojo.getContext("2d");
contextoRojo.fillStyle = "red";
contextoRojo.fillRect (20, 20, 40, 40);
var miCanvasVerde = document.getElementById("miCanvasVerde");
var contextoVerde = miCanvasVerde.getContext("2d");
contextoVerde.fillStyle = "green";
contextoVerde.fillRect (20, 20, 60, 60);
var miCanvasAzul = document.getElementById("miCanvasAzul");
var contextoAzul = miCanvasAzul.getContext("2d");
contextoAzul.fillStyle = "blue";
contextoAzul.fillRect (40, 40, 40, 40);
